server:
  port: 8083


spring:
  datasource:
    data: classpath:sql/data.sql
    schema: classpath:sql/schema.sql
    url: jdbc:h2:file:./build/data/productsdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
    initialization-mode: always
