server:
  port: 8083


spring:
  datasource:
    url: jdbc:h2:file:./build/data/productsdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  sql:
    init:
      data-locations: classpath:sql/data.sql
      schema-locations: classpath:sql/schema.sql
      mode: always
